name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t mofazzal874/gemini-clone:latest .
          docker push mofazzal874/gemini-clone:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Cloud Server via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.CLOUD_SERVER_IP }}
          username: ${{ secrets.CLOUD_SERVER_USER }}
          password: ${{ secrets.CLOUD_SERVER_PASSWORD }}
          script: |
            set -e  # Exit immediately if a command fails
            
            # Create the project directory if it doesn't exist
            mkdir -p /root/gemini-clone
            
            # Pull the latest Docker image
            docker pull mofazzal874/gemini-clone:latest
            
            # Stop existing container if it exists
            docker stop gemini-clone || true
            
            # Remove the container if it exists
            docker rm gemini-clone || true

            # Create .env file with the API key in the project directory
            echo "VITE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" > /root/gemini-clone/.env

            # Run the Docker container with the .env file, passing the API key as an environment variable
            docker run -d -p 9000:80 \
              --name gemini-clone \
              --env-file /root/gemini-clone/.env \
              mofazzal874/gemini-clone:latest
